### ISSUE TITLE
the default username?

### ISSUE THREAD

**Issue by zhujq** [free5gmano/free5gmano#12]
Hi there,
      I have deployed free5gmano and kube5gnfo，when I tried to use chrome to login in free5gmano on port 30088，such as http://xx.xx.xx.xx:30088/admin,a log in windows is showed,what is the default usename and password?I tried admin/free5gc, admin/admin, failed,and I have opened mysql database of free5gmano,it seemed that there is no content in table auth_user,so Is there a default user of free5gmano? and how i can create one ?

**Comment by cewuandy** [comment]
Hello,
The admin page is not for using directly. You should use free5gmano to call the kube5gnfvo api through the os-ma-nfvo interface. You can read [free5gmano](https://github.com/free5gmano/free5gmano#getting-started)markdown and step by step install it.
Thanks.
