### ISSUE TITLE
"Command 'nmctl' not found" Despite Successful Install

### ISSUE THREAD

**Issue by thegorski** [free5gmano/free5gmano#33]
I am using the free5gmano-cli installation guide to install nmctl. My assumption is that the following command installs nmctl:

`pip3 install -e .`

Running this command outputs the following: 

`Successfully installed click-7.1 nmctl numpy-1.18.5 pandas-0.24.2 python-dateutil-2.8.1 pytz-2020.1 six-1.15.0`

However, I having issues in the "Apply NSSI" section.

`git clone https://github.com/free5gmano/simpleexampleplugin.git`
`nmctl register plugin kube5gnfvo -f simpleexampleplugin/`
`Command 'nmctl' not found, did you mean:
    command 'nsctl' from deb l2tpns
 Try: sudo apt install <deb name>`

How do I properly install nmctl?

**Comment by Samcandy** [comment]
Hi @thegorski, 
This is a permission problem that prevents the command from being added to /usr/local/bin/. 
You can use `sudo` to perform the installation to avoid this problem. 
For example, the following command: `sudo pip install -e .`

**Comment by thegorski** [comment]
@Samcandy, thanks very much. This solved the issue of nmctl being recognized.
