### ISSUE TITLE
[free5gmano] Meet the problem when setting up free5gc with K8S

### ISSUE THREAD

**Issue by willie-hsueh-666** [free5gmano/free5gmano#40]
[nrf_pod_describe.txt](https://github.com/free5gmano/free5gmano/files/5332772/nrf_pod_describe.txt)

Hi free5gcmano team,
We would like to set up free5gc with K8S and use the yaml you provided in the /deploy/free5gc-stage-3, but suffer from some problems.
Below is our set up steps:

1.	Install kube5gnfvo: in this step, we set up the following items
   kubectl apply -f multus-daemonset-pre-1.16.yml
   ovs-vsctl add-br br1
   kubectl apply -f ovs-cni.yaml
   kubectl apply -f ovs-net-crd.yaml
2.	Go to deploy/free5gc-stage-3 and do the following steps:
   kubectl apply –f unix-daemonset.yaml
   kubectl apply –f free5gc-configmap.yaml
   kubectl apply –f free5gc-nrf.yaml

Then, we find that the NRF pod crashed continusely.

Below is the log of NRF pod: kubectl logs free5gc-nrf-deployment-5585d4fc95-85gl9 init-network-client
2020/10/06 08:37:04 Start to connect to  unix:///tmp/vortex.sock
2020/10/06 08:37:04 free5gc-nrf-deployment-5585d4fc95-85gl9 default 783fac46-31f7-4e41-aa21-1079f08a6544
2020/10/06 08:37:04 Try to find the network namespace path
2020/10/06 08:37:04 Find network namesace path is sussessful.
2020/10/06 08:37:04 The path is /var/run/docker/netns/11e596880773.
2020/10/06 08:37:04 Try to connect bridge /var/run/docker/netns/11e596880773 eth1 br0
2020/10/06 08:37:04 There is something wrong with connect bridge: rpc error: code = Unknown desc = file exists

And the pod describe is in the attachment.

Could you help to check the problem and share how to set up the free5gc by K8S with your yaml?

Thanks,
Willie

**Comment by yanyan8566** [comment]
Hi @willie-hsueh-666 ,

Please try the new version free5gc-stage-3.0.4 , and deploy then from 00 to 12 .

By the way , the ovs br need to add br0 , please use this command : 
ovs-vsctl add-br br0

Wish this help you .

Thanks

**Comment by PallaviTharigonda** [comment]
@willie-hsueh-666 is this working for you? Actually I also  got similar kind of issue.My pods are also not running and I'm getting crashloopbackoff error.If you provide details about how you resolved..It'll be much helpful:)
